version: "2"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80

  frontend:
    build: ./frontend
    restart: on-failure
    expose:
      - 4201
    environment:
      - VIRTUAL_HOST=${FRONTEND_HOST}
    volumes:
      - ./frontend-env-local.json:/home/payment-init-demo-app/deploy/dist/assets/environments/environment.json
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: on-failure
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=${BACKEND_HOST}
      - REDIRECT_URL=${REDIRECT_URL}
      - WELL_KNOWN_URL=${OIDC_WELL_KNOWN_URL}
      - MONGO_CONNECTION=demoappmongodb://mongodb:27017/demo
      - CLIENT_SECRET=${CLIENT_SECRET}
      - PAYMENT_INIT_API_URL=${PAYMENT_INIT_API_URL}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - CLIENT_ID=${CLIENT_ID}
      - PORT=8080
      - AUTH_SERVER_BASE_PATH=${AUTH_SERVER_BASE_PATH}
    depends_on:
      - demoappmongodb

  demoappmongodb:
    image: mongo
    ports:
      - 27017:27017