/**
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { OBErrorResponse1 } from '../model/oBErrorResponse1';
import { OBWriteFundsConfirmationResponse1 } from '../model/oBWriteFundsConfirmationResponse1';
import { OBWriteInternational2 } from '../model/oBWriteInternational2';
import { OBWriteInternationalConsent2 } from '../model/oBWriteInternationalConsent2';
import { OBWriteInternationalConsentResponse2 } from '../model/oBWriteInternationalConsentResponse2';
import { OBWriteInternationalResponse2 } from '../model/oBWriteInternationalResponse2';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { environment } from './../../../environments/environment';


@Injectable()
export class InternationalPaymentsService {

    protected basePath = environment.apiUrl+ '/open-banking/v3.1/pisp';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Add International Payments
     * 
     * @param OBWriteInternationalConsent2Param Default
     * @param Authorization An Authorisation Token as per https://tools.ietf.org/html/rfc6750
     * @param x_idempotency_key Every request will be processed only once per x-idempotency-key.  The Idempotency Key will be valid for 24 hours.
     * @param x_fapi_financial_id The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.
     * @param x_fapi_customer_last_logged_time The time when the PSU last logged in with the TPP. All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: Sun, 10 Sep 2017 19:43:31 UTC
     * @param x_fapi_customer_ip_address The PSU&#39;s IP address if the PSU is currently logged in with the TPP.
     * @param x_fapi_interaction_id An RFC4122 UID used as a correlation id.
     * @param x_jws_signature A detached JWS signature of the body of the payload.
     * @param x_customer_user_agent Indicates the user-agent that the PSU is using.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createInternationalPaymentConsents(OBWriteInternationalConsent2Param: OBWriteInternationalConsent2, Authorization: string, x_idempotency_key: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_jws_signature?: string, x_customer_user_agent?: string, observe?: 'body', reportProgress?: boolean): Observable<OBWriteInternationalConsentResponse2>;
    public createInternationalPaymentConsents(OBWriteInternationalConsent2Param: OBWriteInternationalConsent2, Authorization: string, x_idempotency_key: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_jws_signature?: string, x_customer_user_agent?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OBWriteInternationalConsentResponse2>>;
    public createInternationalPaymentConsents(OBWriteInternationalConsent2Param: OBWriteInternationalConsent2, Authorization: string, x_idempotency_key: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_jws_signature?: string, x_customer_user_agent?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OBWriteInternationalConsentResponse2>>;
    public createInternationalPaymentConsents(OBWriteInternationalConsent2Param: OBWriteInternationalConsent2, Authorization: string, x_idempotency_key: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_jws_signature?: string, x_customer_user_agent?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (OBWriteInternationalConsent2Param === null || OBWriteInternationalConsent2Param === undefined) {
            throw new Error('Required parameter OBWriteInternationalConsent2Param was null or undefined when calling createInternationalPaymentConsents.');
        }
        if (Authorization === null || Authorization === undefined) {
            throw new Error('Required parameter Authorization was null or undefined when calling createInternationalPaymentConsents.');
        }
        if (x_idempotency_key === null || x_idempotency_key === undefined) {
            throw new Error('Required parameter x_idempotency_key was null or undefined when calling createInternationalPaymentConsents.');
        }

        let headers = this.defaultHeaders;
        if (x_fapi_financial_id !== undefined && x_fapi_financial_id !== null) {
            headers = headers.set('x-fapi-financial-id', String(x_fapi_financial_id));
        }
        if (x_fapi_customer_last_logged_time !== undefined && x_fapi_customer_last_logged_time !== null) {
            headers = headers.set('x-fapi-customer-last-logged-time', String(x_fapi_customer_last_logged_time));
        }
        if (x_fapi_customer_ip_address !== undefined && x_fapi_customer_ip_address !== null) {
            headers = headers.set('x-fapi-customer-ip-address', String(x_fapi_customer_ip_address));
        }
        if (x_fapi_interaction_id !== undefined && x_fapi_interaction_id !== null) {
            headers = headers.set('x-fapi-interaction-id', String(x_fapi_interaction_id));
        }
        if (Authorization !== undefined && Authorization !== null) {
            headers = headers.set('Authorization', String(Authorization));
        }
        if (x_idempotency_key !== undefined && x_idempotency_key !== null) {
            headers = headers.set('x-idempotency-key', String(x_idempotency_key));
        }
        if (x_jws_signature !== undefined && x_jws_signature !== null) {
            headers = headers.set('x-jws-signature', String(x_jws_signature));
        }
        if (x_customer_user_agent !== undefined && x_customer_user_agent !== null) {
            headers = headers.set('x-customer-user-agent', String(x_customer_user_agent));
        }

        // authentication (TPPOAuth2Security) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json; charset=utf-8'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json; charset=utf-8'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<OBWriteInternationalConsentResponse2>(`${this.basePath}/international-payment-consents`,
            OBWriteInternationalConsent2Param,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create International Payments
     * 
     * @param OBWriteInternational2Param Default
     * @param Authorization An Authorisation Token as per https://tools.ietf.org/html/rfc6750
     * @param x_idempotency_key Every request will be processed only once per x-idempotency-key.  The Idempotency Key will be valid for 24 hours.
     * @param x_fapi_financial_id The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.
     * @param x_fapi_customer_last_logged_time The time when the PSU last logged in with the TPP. All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: Sun, 10 Sep 2017 19:43:31 UTC
     * @param x_fapi_customer_ip_address The PSU&#39;s IP address if the PSU is currently logged in with the TPP.
     * @param x_fapi_interaction_id An RFC4122 UID used as a correlation id.
     * @param x_jws_signature A detached JWS signature of the body of the payload.
     * @param x_customer_user_agent Indicates the user-agent that the PSU is using.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createInternationalPayments(OBWriteInternational2Param: OBWriteInternational2, Authorization: string, x_idempotency_key: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_jws_signature?: string, x_customer_user_agent?: string, observe?: 'body', reportProgress?: boolean): Observable<OBWriteInternationalResponse2>;
    public createInternationalPayments(OBWriteInternational2Param: OBWriteInternational2, Authorization: string, x_idempotency_key: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_jws_signature?: string, x_customer_user_agent?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OBWriteInternationalResponse2>>;
    public createInternationalPayments(OBWriteInternational2Param: OBWriteInternational2, Authorization: string, x_idempotency_key: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_jws_signature?: string, x_customer_user_agent?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OBWriteInternationalResponse2>>;
    public createInternationalPayments(OBWriteInternational2Param: OBWriteInternational2, Authorization: string, x_idempotency_key: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_jws_signature?: string, x_customer_user_agent?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (OBWriteInternational2Param === null || OBWriteInternational2Param === undefined) {
            throw new Error('Required parameter OBWriteInternational2Param was null or undefined when calling createInternationalPayments.');
        }
        if (Authorization === null || Authorization === undefined) {
            throw new Error('Required parameter Authorization was null or undefined when calling createInternationalPayments.');
        }
        if (x_idempotency_key === null || x_idempotency_key === undefined) {
            throw new Error('Required parameter x_idempotency_key was null or undefined when calling createInternationalPayments.');
        }

        let headers = this.defaultHeaders;
        if (x_fapi_financial_id !== undefined && x_fapi_financial_id !== null) {
            headers = headers.set('x-fapi-financial-id', String(x_fapi_financial_id));
        }
        if (x_fapi_customer_last_logged_time !== undefined && x_fapi_customer_last_logged_time !== null) {
            headers = headers.set('x-fapi-customer-last-logged-time', String(x_fapi_customer_last_logged_time));
        }
        if (x_fapi_customer_ip_address !== undefined && x_fapi_customer_ip_address !== null) {
            headers = headers.set('x-fapi-customer-ip-address', String(x_fapi_customer_ip_address));
        }
        if (x_fapi_interaction_id !== undefined && x_fapi_interaction_id !== null) {
            headers = headers.set('x-fapi-interaction-id', String(x_fapi_interaction_id));
        }
        if (Authorization !== undefined && Authorization !== null) {
            headers = headers.set('Authorization', String(Authorization));
        }
        if (x_idempotency_key !== undefined && x_idempotency_key !== null) {
            headers = headers.set('x-idempotency-key', String(x_idempotency_key));
        }
        if (x_jws_signature !== undefined && x_jws_signature !== null) {
            headers = headers.set('x-jws-signature', String(x_jws_signature));
        }
        if (x_customer_user_agent !== undefined && x_customer_user_agent !== null) {
            headers = headers.set('x-customer-user-agent', String(x_customer_user_agent));
        }

        // authentication (PSUOAuth2Security) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json; charset=utf-8'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json; charset=utf-8'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<OBWriteInternationalResponse2>(`${this.basePath}/international-payments`,
            OBWriteInternational2Param,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get International Payment Consent
     * 
     * @param ConsentId ConsentId
     * @param Authorization An Authorisation Token as per https://tools.ietf.org/html/rfc6750
     * @param x_fapi_financial_id The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.
     * @param x_fapi_customer_last_logged_time The time when the PSU last logged in with the TPP. All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: Sun, 10 Sep 2017 19:43:31 UTC
     * @param x_fapi_customer_ip_address The PSU&#39;s IP address if the PSU is currently logged in with the TPP.
     * @param x_fapi_interaction_id An RFC4122 UID used as a correlation id.
     * @param x_customer_user_agent Indicates the user-agent that the PSU is using.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getInternationalPaymentConsentsConsentId(ConsentId: string, Authorization: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_customer_user_agent?: string, observe?: 'body', reportProgress?: boolean): Observable<OBWriteInternationalConsentResponse2>;
    public getInternationalPaymentConsentsConsentId(ConsentId: string, Authorization: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_customer_user_agent?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OBWriteInternationalConsentResponse2>>;
    public getInternationalPaymentConsentsConsentId(ConsentId: string, Authorization: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_customer_user_agent?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OBWriteInternationalConsentResponse2>>;
    public getInternationalPaymentConsentsConsentId(ConsentId: string, Authorization: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_customer_user_agent?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (ConsentId === null || ConsentId === undefined) {
            throw new Error('Required parameter ConsentId was null or undefined when calling getInternationalPaymentConsentsConsentId.');
        }
        if (Authorization === null || Authorization === undefined) {
            throw new Error('Required parameter Authorization was null or undefined when calling getInternationalPaymentConsentsConsentId.');
        }

        let headers = this.defaultHeaders;
        if (x_fapi_financial_id !== undefined && x_fapi_financial_id !== null) {
            headers = headers.set('x-fapi-financial-id', String(x_fapi_financial_id));
        }
        if (x_fapi_customer_last_logged_time !== undefined && x_fapi_customer_last_logged_time !== null) {
            headers = headers.set('x-fapi-customer-last-logged-time', String(x_fapi_customer_last_logged_time));
        }
        if (x_fapi_customer_ip_address !== undefined && x_fapi_customer_ip_address !== null) {
            headers = headers.set('x-fapi-customer-ip-address', String(x_fapi_customer_ip_address));
        }
        if (x_fapi_interaction_id !== undefined && x_fapi_interaction_id !== null) {
            headers = headers.set('x-fapi-interaction-id', String(x_fapi_interaction_id));
        }
        if (Authorization !== undefined && Authorization !== null) {
            headers = headers.set('Authorization', String(Authorization));
        }
        if (x_customer_user_agent !== undefined && x_customer_user_agent !== null) {
            headers = headers.set('x-customer-user-agent', String(x_customer_user_agent));
        }

        // authentication (TPPOAuth2Security) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json; charset=utf-8'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json; charset=utf-8'
        ];

        return this.httpClient.get<OBWriteInternationalConsentResponse2>(`${this.basePath}/international-payment-consents/${encodeURIComponent(String(ConsentId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get International Payment Consent Funds Confirmation
     * 
     * @param ConsentId ConsentId
     * @param Authorization An Authorisation Token as per https://tools.ietf.org/html/rfc6750
     * @param x_fapi_financial_id The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.
     * @param x_fapi_customer_last_logged_time The time when the PSU last logged in with the TPP. All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: Sun, 10 Sep 2017 19:43:31 UTC
     * @param x_fapi_customer_ip_address The PSU&#39;s IP address if the PSU is currently logged in with the TPP.
     * @param x_fapi_interaction_id An RFC4122 UID used as a correlation id.
     * @param x_customer_user_agent Indicates the user-agent that the PSU is using.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getInternationalPaymentConsentsConsentIdFundsConfirmation(ConsentId: string, Authorization: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_customer_user_agent?: string, observe?: 'body', reportProgress?: boolean): Observable<OBWriteFundsConfirmationResponse1>;
    public getInternationalPaymentConsentsConsentIdFundsConfirmation(ConsentId: string, Authorization: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_customer_user_agent?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OBWriteFundsConfirmationResponse1>>;
    public getInternationalPaymentConsentsConsentIdFundsConfirmation(ConsentId: string, Authorization: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_customer_user_agent?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OBWriteFundsConfirmationResponse1>>;
    public getInternationalPaymentConsentsConsentIdFundsConfirmation(ConsentId: string, Authorization: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_customer_user_agent?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (ConsentId === null || ConsentId === undefined) {
            throw new Error('Required parameter ConsentId was null or undefined when calling getInternationalPaymentConsentsConsentIdFundsConfirmation.');
        }
        if (Authorization === null || Authorization === undefined) {
            throw new Error('Required parameter Authorization was null or undefined when calling getInternationalPaymentConsentsConsentIdFundsConfirmation.');
        }

        let headers = this.defaultHeaders;
        if (x_fapi_financial_id !== undefined && x_fapi_financial_id !== null) {
            headers = headers.set('x-fapi-financial-id', String(x_fapi_financial_id));
        }
        if (x_fapi_customer_last_logged_time !== undefined && x_fapi_customer_last_logged_time !== null) {
            headers = headers.set('x-fapi-customer-last-logged-time', String(x_fapi_customer_last_logged_time));
        }
        if (x_fapi_customer_ip_address !== undefined && x_fapi_customer_ip_address !== null) {
            headers = headers.set('x-fapi-customer-ip-address', String(x_fapi_customer_ip_address));
        }
        if (x_fapi_interaction_id !== undefined && x_fapi_interaction_id !== null) {
            headers = headers.set('x-fapi-interaction-id', String(x_fapi_interaction_id));
        }
        if (Authorization !== undefined && Authorization !== null) {
            headers = headers.set('Authorization', String(Authorization));
        }
        if (x_customer_user_agent !== undefined && x_customer_user_agent !== null) {
            headers = headers.set('x-customer-user-agent', String(x_customer_user_agent));
        }

        // authentication (PSUOAuth2Security) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json; charset=utf-8'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json; charset=utf-8'
        ];

        return this.httpClient.get<OBWriteFundsConfirmationResponse1>(`${this.basePath}/international-payment-consents/${encodeURIComponent(String(ConsentId))}/funds-confirmation`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get International Payment
     * 
     * @param InternationalPaymentId InternationalPaymentId
     * @param Authorization An Authorisation Token as per https://tools.ietf.org/html/rfc6750
     * @param x_fapi_financial_id The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.
     * @param x_fapi_customer_last_logged_time The time when the PSU last logged in with the TPP. All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: Sun, 10 Sep 2017 19:43:31 UTC
     * @param x_fapi_customer_ip_address The PSU&#39;s IP address if the PSU is currently logged in with the TPP.
     * @param x_fapi_interaction_id An RFC4122 UID used as a correlation id.
     * @param x_customer_user_agent Indicates the user-agent that the PSU is using.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getInternationalPaymentsInternationalPaymentId(InternationalPaymentId: string, Authorization: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_customer_user_agent?: string, observe?: 'body', reportProgress?: boolean): Observable<OBWriteInternationalResponse2>;
    public getInternationalPaymentsInternationalPaymentId(InternationalPaymentId: string, Authorization: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_customer_user_agent?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OBWriteInternationalResponse2>>;
    public getInternationalPaymentsInternationalPaymentId(InternationalPaymentId: string, Authorization: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_customer_user_agent?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OBWriteInternationalResponse2>>;
    public getInternationalPaymentsInternationalPaymentId(InternationalPaymentId: string, Authorization: string, x_fapi_financial_id?: string, x_fapi_customer_last_logged_time?: string, x_fapi_customer_ip_address?: string, x_fapi_interaction_id?: string, x_customer_user_agent?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (InternationalPaymentId === null || InternationalPaymentId === undefined) {
            throw new Error('Required parameter InternationalPaymentId was null or undefined when calling getInternationalPaymentsInternationalPaymentId.');
        }
        if (Authorization === null || Authorization === undefined) {
            throw new Error('Required parameter Authorization was null or undefined when calling getInternationalPaymentsInternationalPaymentId.');
        }

        let headers = this.defaultHeaders;
        if (x_fapi_financial_id !== undefined && x_fapi_financial_id !== null) {
            headers = headers.set('x-fapi-financial-id', String(x_fapi_financial_id));
        }
        if (x_fapi_customer_last_logged_time !== undefined && x_fapi_customer_last_logged_time !== null) {
            headers = headers.set('x-fapi-customer-last-logged-time', String(x_fapi_customer_last_logged_time));
        }
        if (x_fapi_customer_ip_address !== undefined && x_fapi_customer_ip_address !== null) {
            headers = headers.set('x-fapi-customer-ip-address', String(x_fapi_customer_ip_address));
        }
        if (x_fapi_interaction_id !== undefined && x_fapi_interaction_id !== null) {
            headers = headers.set('x-fapi-interaction-id', String(x_fapi_interaction_id));
        }
        if (Authorization !== undefined && Authorization !== null) {
            headers = headers.set('Authorization', String(Authorization));
        }
        if (x_customer_user_agent !== undefined && x_customer_user_agent !== null) {
            headers = headers.set('x-customer-user-agent', String(x_customer_user_agent));
        }

        // authentication (TPPOAuth2Security) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json; charset=utf-8'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json; charset=utf-8'
        ];

        return this.httpClient.get<OBWriteInternationalResponse2>(`${this.basePath}/international-payments/${encodeURIComponent(String(InternationalPaymentId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
