/**
 * Payment Initiation API Specification
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Unambiguous identification of the account of the creditor to which a credit entry will be posted as a result of the payment transaction.
 */
export interface CreditorAccount {
    /**
     * Name of the identification scheme, in a coded form as published in an external list.
     */
    SchemeName: CreditorAccount.SchemeNameEnum;
    /**
     * Identification assigned by an institution to identify an account. This identification is known by the account owner.
     */
    Identification: string;
    /**
     * Name of the account, as assigned by the account servicing institution, in agreement with the account owner in order to provide an additional means of identification of the account. Usage: The account name is different from the account owner name. The account name is used in certain user communities to provide a means of identifying the account, in addition to the account owner's identity and the account number. ASPSPs may carry out name validation for Confirmation of Payee, but it is not mandatory.
     */
    Name: string;
    /**
     * This is secondary identification of the account, as assigned by the account servicing institution. This can be used by building societies to additionally identify accounts with a roll number (in addition to a sort code and account number combination).
     */
    SecondaryIdentification?: string;
}
export namespace CreditorAccount {
    export type SchemeNameEnum = 'BBAN' | 'IBAN';
    export const SchemeNameEnum = {
        BBAN: 'BBAN' as SchemeNameEnum,
        IBAN: 'IBAN' as SchemeNameEnum
    }
}
