/**
 * Payment Initiation API Specification
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Financial institution servicing an account for the creditor.
 */
export interface CreditorAgent1 {
    /**
     * Name of the identification scheme, in a coded form as published in an external list.
     */
    SchemeName: CreditorAgent1.SchemeNameEnum;
    /**
     * Unique and unambiguous identification of a person.
     */
    Identification: string;
}
export namespace CreditorAgent1 {
    export type SchemeNameEnum = 'BICFI' | 'UKSortCode';
    export const SchemeNameEnum = {
        BICFI: 'BICFI' as SchemeNameEnum,
        UKSortCode: 'UKSortCode' as SchemeNameEnum
    }
}
