/**
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBExternalFinancialInstitutionIdentification4Code } from './oBExternalFinancialInstitutionIdentification4Code';
import { OBPostalAddress6 } from './oBPostalAddress6';


/**
 * Party that manages the account on behalf of the account owner, that is manages the registration and booking of entries on the account, calculates balances on the account and provides information about the account. This is the servicer of the beneficiary account.
 */
export interface OBBranchAndFinancialInstitutionIdentification6 {
    SchemeName?: OBExternalFinancialInstitutionIdentification4Code;
    /**
     * Unique and unambiguous identification of the servicing institution.
     */
    Identification?: string;
    /**
     * Name by which an agent is known and which is usually used to identify that agent.
     */
    Name?: string;
    PostalAddress?: OBPostalAddress6;
}
