/**
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBCharge2Amount } from './oBCharge2Amount';
import { OBChargeBearerType1Code } from './oBChargeBearerType1Code';
import { OBExternalPaymentChargeType1Code } from './oBExternalPaymentChargeType1Code';


/**
 * Set of elements used to provide details of a charge for the payment initiation.
 */
export interface OBCharge2 {
    ChargeBearer: OBChargeBearerType1Code;
    Type: OBExternalPaymentChargeType1Code;
    Amount: OBCharge2Amount;
}
