/**
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Specifies the status of consent resource in code form.
 */
export type OBExternalConsentStatus2Code = 'Authorised' | 'AwaitingAuthorisation' | 'AwaitingUpload' | 'Consumed' | 'Rejected';

export const OBExternalConsentStatus2Code = {
    Authorised: 'Authorised' as OBExternalConsentStatus2Code,
    AwaitingAuthorisation: 'AwaitingAuthorisation' as OBExternalConsentStatus2Code,
    AwaitingUpload: 'AwaitingUpload' as OBExternalConsentStatus2Code,
    Consumed: 'Consumed' as OBExternalConsentStatus2Code,
    Rejected: 'Rejected' as OBExternalConsentStatus2Code
}
