/**
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Type of authorisation flow requested.
 */
export type OBExternalAuthorisation1Code = 'Any' | 'Single';

export const OBExternalAuthorisation1Code = {
    Any: 'Any' as OBExternalAuthorisation1Code,
    Single: 'Single' as OBExternalAuthorisation1Code
}
