/**
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Specifies the payment context
 */
export type OBExternalPaymentContext1Code = 'BillPayment' | 'EcommerceGoods' | 'EcommerceServices' | 'Other' | 'PartyToParty';

export const OBExternalPaymentContext1Code = {
    BillPayment: 'BillPayment' as OBExternalPaymentContext1Code,
    EcommerceGoods: 'EcommerceGoods' as OBExternalPaymentContext1Code,
    EcommerceServices: 'EcommerceServices' as OBExternalPaymentContext1Code,
    Other: 'Other' as OBExternalPaymentContext1Code,
    PartyToParty: 'PartyToParty' as OBExternalPaymentContext1Code
}
