/**
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Specifies the type used to complete the currency exchange.
 */
export type OBExchangeRateType2Code = 'Actual' | 'Agreed' | 'Indicative';

export const OBExchangeRateType2Code = {
    Actual: 'Actual' as OBExchangeRateType2Code,
    Agreed: 'Agreed' as OBExchangeRateType2Code,
    Indicative: 'Indicative' as OBExchangeRateType2Code
}
