/**
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Specifies the status of the authorisation flow in code form.
 */
export type OBExternalStatus2Code = 'Authorised' | 'AwaitingFurtherAuthorisation' | 'Rejected';

export const OBExternalStatus2Code = {
    Authorised: 'Authorised' as OBExternalStatus2Code,
    AwaitingFurtherAuthorisation: 'AwaitingFurtherAuthorisation' as OBExternalStatus2Code,
    Rejected: 'Rejected' as OBExternalStatus2Code
}
