/**
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBBranchAndFinancialInstitutionIdentification6 } from './oBBranchAndFinancialInstitutionIdentification6';
import { OBCashAccountCreditor3 } from './oBCashAccountCreditor3';
import { OBCashAccountDebtor4 } from './oBCashAccountDebtor4';
import { OBChargeBearerType1Code } from './oBChargeBearerType1Code';
import { OBDomestic2InstructedAmount } from './oBDomestic2InstructedAmount';
import { OBExchangeRate1 } from './oBExchangeRate1';
import { OBExternalLocalInstrument1Code } from './oBExternalLocalInstrument1Code';
import { OBExternalPurpose1Code1 } from './oBExternalPurpose1Code1';
import { OBPartyIdentification43 } from './oBPartyIdentification43';
import { OBPriority2Code } from './oBPriority2Code';
import { OBRemittanceInformation1 } from './oBRemittanceInformation1';
import { OBSupplementaryData1 } from './oBSupplementaryData1';


/**
 * The Initiation payload is sent by the initiating party to the ASPSP. It is used to request movement of funds from the debtor account to a creditor for a single scheduled international payment.
 */
export interface OBInternationalScheduled2 {
    /**
     * Unique identification as assigned by an instructing party for an instructed party to unambiguously identify the instruction. Usage: the  instruction identification is a point to point reference that can be used between the instructing party and the instructed party to refer to the individual instruction. It can be included in several messages related to the instruction.
     */
    InstructionIdentification: string;
    /**
     * Unique identification assigned by the initiating party to unambiguously identify the transaction. This identification is passed on, unchanged, throughout the entire end-to-end chain. Usage: The end-to-end identification can be used for reconciliation or to link tasks relating to the transaction. It can be included in several messages related to the transaction. OB: The Faster Payments Scheme can only access 31 characters for the EndToEndIdentification field.
     */
    EndToEndIdentification?: string;
    LocalInstrument?: OBExternalLocalInstrument1Code;
    InstructionPriority?: OBPriority2Code;
    Purpose?: OBExternalPurpose1Code1;
    ChargeBearer?: OBChargeBearerType1Code;
    /**
     * Date at which the initiating party requests the clearing agent to process the payment. Usage: This is the date on which the debtor's account is to be debited. All dates in the JSON payloads are represented in ISO 8601 date-time format. All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     */
    RequestedExecutionDateTime: Date;
    /**
     * Specifies the currency of the to be transferred amount, which is different from the currency of the debtor's account.
     */
    CurrencyOfTransfer: string;
    InstructedAmount: OBDomestic2InstructedAmount;
    ExchangeRateInformation?: OBExchangeRate1;
    DebtorAccount?: OBCashAccountDebtor4;
    Creditor?: OBPartyIdentification43;
    CreditorAgent?: OBBranchAndFinancialInstitutionIdentification6;
    CreditorAccount: OBCashAccountCreditor3;
    RemittanceInformation?: OBRemittanceInformation1;
    SupplementaryData?: OBSupplementaryData1;
}
