/**
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBExternalStatus2Code } from './oBExternalStatus2Code';


/**
 * The multiple authorisation flow response from the ASPSP.
 */
export interface OBMultiAuthorisation1 {
    Status: OBExternalStatus2Code;
    /**
     * Number of authorisations required for payment order (total required at the start of the multi authorisation journey).
     */
    NumberRequired?: number;
    /**
     * Number of authorisations required for payment order (total required at the start of the multi authorisation journey).
     */
    NumberReceived?: number;
    /**
     * Last date and time at the authorisation flow was updated. All dates in the JSON payloads are represented in ISO 8601 date-time format. All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     */
    LastUpdateDateTime?: Date;
    /**
     * Date and time at which the requested authorisation flow must be completed. All dates in the JSON payloads are represented in ISO 8601 date-time format. All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     */
    ExpirationDateTime?: Date;
}
