/**
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBPostalAddress6 } from './oBPostalAddress6';


/**
 * Party to which an amount of money is due.
 */
export interface OBPartyIdentification43 {
    /**
     * Name by which a party is known and which is usually used to identify that party.
     */
    Name?: string;
    PostalAddress?: OBPostalAddress6;
}
