/**
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Indicator of the urgency or order of importance that the instructing party would like the instructed party to apply to the processing of the instruction.
 */
export type OBPriority2Code = 'Normal' | 'Urgent';

export const OBPriority2Code = {
    Normal: 'Normal' as OBPriority2Code,
    Urgent: 'Urgent' as OBPriority2Code
}
