/**
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBExternalPaymentContext1Code } from './oBExternalPaymentContext1Code';
import { OBRisk1DeliveryAddress } from './oBRisk1DeliveryAddress';


/**
 * The Risk section is sent by the initiating party to the ASPSP. It is used to specify additional details for risk scoring for Payments.
 */
export interface OBRisk1 {
    PaymentContextCode?: OBExternalPaymentContext1Code;
    /**
     * Category code conform to ISO 18245, related to the type of services or goods the merchant provides for the transaction.
     */
    MerchantCategoryCode?: string;
    /**
     * The unique customer identifier of the PSU with the merchant.
     */
    MerchantCustomerIdentification?: string;
    DeliveryAddress?: OBRisk1DeliveryAddress;
}
