/**
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Specifies the status of the payment information group.
 */
export type OBTransactionIndividualStatus1Code = 'AcceptedSettlementCompleted' | 'AcceptedSettlementInProcess' | 'Pending' | 'Rejected';

export const OBTransactionIndividualStatus1Code = {
    AcceptedSettlementCompleted: 'AcceptedSettlementCompleted' as OBTransactionIndividualStatus1Code,
    AcceptedSettlementInProcess: 'AcceptedSettlementInProcess' as OBTransactionIndividualStatus1Code,
    Pending: 'Pending' as OBTransactionIndividualStatus1Code,
    Rejected: 'Rejected' as OBTransactionIndividualStatus1Code
}
