/**
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBRisk1 } from './oBRisk1';
import { OBWriteDataInternationalScheduled2 } from './oBWriteDataInternationalScheduled2';


export interface OBWriteInternationalScheduled2 {
    Data: OBWriteDataInternationalScheduled2;
    Risk: OBRisk1;
}
