/**
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBWriteDataBatchInternational2InternationalPayments } from './oBWriteDataBatchInternational2InternationalPayments';
import { OBWriteDataBatchInternational2InternationalScheduledPayments } from './oBWriteDataBatchInternational2InternationalScheduledPayments';


export interface OBWriteDataBatchInternational2 {
    /**
     * OB: Unique identification as assigned by the ASPSP to uniquely identify the consent resource.
     */
    ConsentId: string;
    InternationalPayments: Array<OBWriteDataBatchInternational2InternationalPayments>;
    InternationalScheduledPayments: Array<OBWriteDataBatchInternational2InternationalScheduledPayments>;
}
