/**
 * Payment Initiation API Specification
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreditorAccount } from './creditorAccount';
import { CreditorAgent1 } from './creditorAgent1';
import { DebtorAccount } from './debtorAccount';
import { DebtorAgent1 } from './debtorAgent1';
import { PaymentSetupInitiationInstructedAmount } from './paymentSetupInitiationInstructedAmount';
import { RemittanceInformation } from './remittanceInformation';


/**
 * The Initiation payload is sent by the initiating party to the ASPSP. It is used to request movement of funds from the debtor account to a creditor.
 */
export interface PaymentSetupResponse1Initiation {
    /**
     * Unique identification as assigned by an instructing party for an instructed party to unambiguously identify the instruction. Usage: the  instruction identification is a point to point reference that can be used between the instructing party and the instructed party to refer to the individual instruction. It can be included in several messages related to the instruction.
     */
    InstructionIdentification: string;
    /**
     * Unique identification assigned by the initiating party to unambiguously identify the transaction. This identification is passed on, unchanged, throughout the entire end-to-end chain. Usage: The end-to-end identification can be used for reconciliation or to link tasks relating to the transaction. It can be included in several messages related to the transaction. OB: The Faster Payments Scheme can only access 31 characters for the EndToEndIdentification field.
     */
    EndToEndIdentification: string;
    InstructedAmount: PaymentSetupInitiationInstructedAmount;
    DebtorAgent?: DebtorAgent1;
    DebtorAccount?: DebtorAccount;
    CreditorAgent: CreditorAgent1;
    CreditorAccount: CreditorAccount;
    RemittanceInformation?: RemittanceInformation;
}
