export enum PaymentConsentType {
  'NONE' = '0',
  'DOMESTIC_PAYMENT_CONSENT'= '1', 
  'DOMESTIC_SCHEDULED_PAYMENT_CONSENT'= '2', 
  'BATCH_INTERNATIONAL_PAYMENT_CONSENT'= '3', 
  'BATCH_DOMESTIC_PAYMENT_CONSENT'= '4', 
  'DOMESTIC_STANDING_ORDER_CONSENT'= '5',
  'INTERNATIONAL_PAYMENT_CONSENT'= '6',
  'INTERNATIONAL_SCHEDULED_PAYMENT_CONSENT'= '7'
}