/**
 * Payment Initiation API Specification
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Links } from './links';
import { Meta } from './meta';
import { PaymentSetupResponse } from './paymentSetupResponse';
import { Risk1 } from './risk1';


export interface PaymentSetupPOSTResponse {
    Data: PaymentSetupResponse;
    Risk: Risk1;
    Links: Links;
    Meta: Meta;
}
