export enum PaymentConsentType {
  NONE,
  DOMESTIC_PAYMENT_CONSENT, 
  DOMESTIC_SCHEDULED_PAYMENT_CONSENT, 
  BATCH_INTERNATIONAL_PAYMENT_CONSENT, 
  BATCH_DOMESTIC_PAYMENT_CONSENT, 
  DOMESTIC_STANDING_ORDER_CONSENT,
  INTERNATIONAL_PAYMENT_CONSENT,
  INTERNATIONAL_SCHEDULED_PAYMENT_CONSENT
}