/**
 * Payment Initiation API Specification
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaymentSubmission } from './paymentSubmission';
import { Risk } from './risk';


/**
 * Allows Submission of a payment
 */
export interface PaymentSubmissionPOSTRequest {
    Data: PaymentSubmission;
    Risk: Risk;
}
