/**
 * Payment Initiation API Specification
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaymentSetupResponse1Initiation } from './paymentSetupResponse1Initiation';


/**
 * 
 */
export interface PaymentSubmission {
    /**
     * OB: Unique identification as assigned by the ASPSP to uniquely identify the payment setup resource.
     */
    PaymentId: string;
    Initiation: PaymentSetupResponse1Initiation;
}
